services:
  mongodb:
    container_name: tubestst2_mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword123
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://admin:securepassword123@mongodb:27017/my-database?authSource=admin
      JWT_SECRET: bespoke_gift_123
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
